BEGIN TRANSACTION;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    email TEXT UNIQUE NOT NULL,
    entries SMALLINT DEFAULT 0,
    registrationDatetime TIME WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMIT;