BEGIN TRANSACTION;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    age SMALLINT,
    pet VARCHAR(32),
    email TEXT UNIQUE NOT NULL,
    entries SMALLINT DEFAULT 0,
    registrationDatetime TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMIT;